set more off
clear all
capture log close
program drop _all
set scheme modern
preliminaries
version 17

program main
    select_good_categories, embed("tfidf")
end

program select_good_categories
    syntax, embed(string)
    import delimited ../external/samp/utdallas_full_report_gatekeeper_tfidf_expert_non_parametric_`embed', clear
    cap rename v1 category
    drop if inlist(category, "macro avg", "weighted avg", "Non-Lab", "accuracy")
    gen tier1 = 0
    gen tier2 = 0
    gen tier3 = 0

    replace tier1 = 1 if category == "begm"
    replace tier1 = 1 if category == "bovine growth serum"
    replace tier1 = 1 if category == "cardiomyocyte tissue media"
    replace tier1 = 1 if category == "corneal tissue media"
    replace tier1 = 1 if category == "dme"
    replace tier1 = 1 if category == "dmem"
    replace tier1 = 1 if category == "dry basal media, not chemically defined"
    replace tier1 = 1 if category == "emem"
    replace tier1 = 1 if category == "gene-specific rnai reagents"
    replace tier1 = 1 if category == "hams f12"
    replace tier1 = 1 if category == "hepatocyte wash medium"
    replace tier1 = 1 if category == "imdm"
    replace tier1 = 1 if category == "insect cell media"
    replace tier1 = 1 if category == "keratinocyte tissue media"
    replace tier1 = 1 if category == "leibovitz l15 media"
    replace tier1 = 1 if category == "liver media"
    replace tier1 = 1 if category == "magnetic bead-based mrna selection kit"
    replace tier1 = 1 if category == "magnetic ip kit"
    replace tier1 = 1 if category == "magnetic polystyrene beads"
    replace tier1 = 1 if category == "mccoys 5a"
    replace tier1 = 1 if category == "medium 199"
    replace tier1 = 1 if category == "megm"
    replace tier1 = 1 if category == "mem"
    replace tier1 = 1 if category == "neural media"
    replace tier1 = 1 if category == "neurobasal medium"
    replace tier1 = 1 if category == "new zealand fbs"
    replace tier1 = 1 if category == "optimem"
    replace tier1 = 1 if category == "prostate breast media"
    replace tier1 = 1 if category == "rpmi"
    replace tier1 = 1 if category == "sirna buffer"
    replace tier1 = 1 if category == "sirna dilution buffer"
    replace tier1 = 1 if category == "sirna transfection medium"
    replace tier1 = 1 if category == "sirna transfection reagents"
    replace tier1 = 1 if category == "smem"
    replace tier1 = 1 if category == "stem cell media"
    replace tier1 = 1 if category == "streptavidin magnetic polystyrene beads"
    replace tier1 = 1 if category == "synthetic shrna"
    replace tier1 = 1 if category == "synthetic sirna"
    replace tier1 = 1 if category == "t-medium"
    replace tier1 = 1 if category == "us fbs"

    *-------------------------------------------------------------------------------
    * TIER 2: LIKELY TREATED
    * EU investigated, confirmed both firms had competing product lines.
    * Cleared without remedies but genuine overlap existed.
    *-------------------------------------------------------------------------------
    replace tier2 = 1 if category == "acrylamide/bis solution"
    replace tier2 = 1 if category == "bca protein assay kit"
    replace tier2 = 1 if category == "bioconjugation reagents"
    replace tier2 = 1 if category == "blunt-end cloning kits"
    replace tier2 = 1 if category == "bradford protein assay kit"
    replace tier2 = 1 if category == "chemically competent cells"
    replace tier2 = 1 if category == "chemiluminescence western blotting kit"
    replace tier2 = 1 if category == "chemiluminescent substrates"
    replace tier2 = 1 if category == "column-based dna and rna extraction kits"
    replace tier2 = 1 if category == "column-based dna genomic purification kits"
    replace tier2 = 1 if category == "column-based dna heparin purification kits"
    replace tier2 = 1 if category == "column-based dna plasmid maxiprep"
    replace tier2 = 1 if category == "column-based dna plasmid megaprep"
    replace tier2 = 1 if category == "column-based dna plasmid midiprep"
    replace tier2 = 1 if category == "column-based dna plasmid miniprep"
    replace tier2 = 1 if category == "column-based dna purification kits"
    replace tier2 = 1 if category == "column-based gel dna extraction kits"
    replace tier2 = 1 if category == "column-based gel rna extraction kits"
    replace tier2 = 1 if category == "column-based microbial dna purification kits"
    replace tier2 = 1 if category == "column-based pcr and gel purification kit"
    replace tier2 = 1 if category == "column-based pcr purification kits"
    replace tier2 = 1 if category == "column-based rna miniprep"
    replace tier2 = 1 if category == "column-based rna purification kits"
    replace tier2 = 1 if category == "crosslinking reagents"
    replace tier2 = 1 if category == "dna polymerase i"
    replace tier2 = 1 if category == "dntps"
    replace tier2 = 1 if category == "dye-based qpcr systems"
    replace tier2 = 1 if category == "electrocompetent cells"
    replace tier2 = 1 if category == "first-strand cdna synthesis systems"
    replace tier2 = 1 if category == "fluorophore - bioconjugate dyes"
    replace tier2 = 1 if category == "fluorophore - general"
    replace tier2 = 1 if category == "gateway cloning kits"
    replace tier2 = 1 if category == "gel blotting papers"
    replace tier2 = 1 if category == "gel electrophoresis power supplies"
    replace tier2 = 1 if category == "high-fidelity dna polymerase"
    replace tier2 = 1 if category == "high-fidelity hot start dna polymerase"
    replace tier2 = 1 if category == "high-fidelity hot start pcr systems"
    replace tier2 = 1 if category == "high-fidelity pcr systems"
    replace tier2 = 1 if category == "horizontal electrophoresis systems"
    replace tier2 = 1 if category == "hot start dna polymerase"
    replace tier2 = 1 if category == "hot start pcr systems"
    replace tier2 = 1 if category == "ligation reaction buffer"
    replace tier2 = 1 if category == "liquid-based dna plasmid purification kit"
    replace tier2 = 1 if category == "long template pcr systems"
    replace tier2 = 1 if category == "magnetic bacterial rna purification kit"
    replace tier2 = 1 if category == "magnetic-bead based purification kit"
    replace tier2 = 1 if category == "microrna reverse transcription kit"
    replace tier2 = 1 if category == "modified lowry protein assay kit"
    replace tier2 = 1 if category == "nitrocellulose blotting membranes"
    replace tier2 = 1 if category == "north/south chemiluminescent detection kit"
    replace tier2 = 1 if category == "nucleic acid gel stains"
    replace tier2 = 1 if category == "nucleic acid modifying enzymes"
    replace tier2 = 1 if category == "pcr barcoding expansion"
    replace tier2 = 1 if category == "pcr systems"
    replace tier2 = 1 if category == "pegylation reagents"
    replace tier2 = 1 if category == "plasmid vectors"
    replace tier2 = 1 if category == "polyacrylamide gels casting kit"
    replace tier2 = 1 if category == "pre amplification kits"
    replace tier2 = 1 if category == "pre-cast bis-tris gels"
    replace tier2 = 1 if category == "pre-cast tbe gels"
    replace tier2 = 1 if category == "pre-cast tris-glycine gels"
    replace tier2 = 1 if category == "pre-cast tris-tricine gels"
    replace tier2 = 1 if category == "pre-stained dna ladders"
    replace tier2 = 1 if category == "pre-stained protein molecular-weight ladder"
    replace tier2 = 1 if category == "pre-stained rna ladders"
    replace tier2 = 1 if category == "precut nitrocellulose transfer blotting packs"
    replace tier2 = 1 if category == "precut pvdf transfer blotting packs"
    replace tier2 = 1 if category == "probe-based qpcr systems"
    replace tier2 = 1 if category == "probe-based rt-qpcr systems"
    replace tier2 = 1 if category == "protein gel stains"
    replace tier2 = 1 if category == "protein labeling kits"
    replace tier2 = 1 if category == "protein modifying enzymes"
    replace tier2 = 1 if category == "pvdf blotting membranes"
    replace tier2 = 1 if category == "qpcr beads"
    replace tier2 = 1 if category == "qrt-pcr titration kit"
    replace tier2 = 1 if category == "quantum dots"
    replace tier2 = 1 if category == "rapid dna ligation kits"
    replace tier2 = 1 if category == "restriction enzymes"
    replace tier2 = 1 if category == "reverse transcriptase"
    replace tier2 = 1 if category == "rna extraction reagents"
    replace tier2 = 1 if category == "rna stabilization reagent"
    replace tier2 = 1 if category == "rt-pcr systems"
    replace tier2 = 1 if category == "seamless cloning kits"
    replace tier2 = 1 if category == "silica bead based gel purification kit"
    replace tier2 = 1 if category == "site-directed mutagenesis systems"
    replace tier2 = 1 if category == "specialized pcr reaction buffer"
    replace tier2 = 1 if category == "spin columns"
    replace tier2 = 1 if category == "synthetic bacterial expression plasmids"
    replace tier2 = 1 if category == "synthetic dna oligonucleotide"
    replace tier2 = 1 if category == "synthetic dna primers"
    replace tier2 = 1 if category == "synthetic dsdna gene fragment"
    replace tier2 = 1 if category == "synthetic dual-labeled probe"
    replace tier2 = 1 if category == "synthetic gene constructs"
    replace tier2 = 1 if category == "synthetic mammalian expression plasmids"
    replace tier2 = 1 if category == "synthetic rna oligonucleotide"
    replace tier2 = 1 if category == "ta cloning kits"
    replace tier2 = 1 if category == "taq buffers"
    replace tier2 = 1 if category == "taq dna ligases"
    replace tier2 = 1 if category == "taq polymerases"
    replace tier2 = 1 if category == "tissue pcr systems"
    replace tier2 = 1 if category == "total protein assay kit"
    replace tier2 = 1 if category == "transfection kits"
    replace tier2 = 1 if category == "transfection reagents"
    replace tier2 = 1 if category == "unstained dna ladders"
    replace tier2 = 1 if category == "unstained protein molecular-weight ladder"
    replace tier2 = 1 if category == "unstained rna ladders"
    replace tier2 = 1 if category == "vertical electrophoresis systems"
    replace tier2 = 1 if category == "western blot blockers"
    replace tier2 = 1 if category == "western blot boxes"
    replace tier2 = 1 if category == "western blot enhancers"
    replace tier2 = 1 if category == "western blot pen"
    replace tier2 = 1 if category == "western blot rollers"
    replace tier2 = 1 if category == "western blot stripping buffers"
    replace tier2 = 1 if category == "western blot transfer buffers"

    replace tier3 = 1 if category == "agarose"
    replace tier3 = 1 if category == "antibody fragment"
    replace tier3 = 1 if category == "antibody kit"
    replace tier3 = 1 if category == "antibody stain block"
    replace tier3 = 1 if category == "antibody-based affinity resins"
    replace tier3 = 1 if category == "apoptosis detection kits"
    replace tier3 = 1 if category == "atp determination kit"
    replace tier3 = 1 if category == "autofluorescence quenching kit"
    replace tier3 = 1 if category == "avidin products"
    replace tier3 = 1 if category == "background suppressor for live cell assays"
    replace tier3 = 1 if category == "bacterial lysis enhancer"
    replace tier3 = 1 if category == "bacterial strain"
    replace tier3 = 1 if category == "bioluminescence assay kit"
    replace tier3 = 1 if category == "bioluminescent immunoassay kit"
    replace tier3 = 1 if category == "biotin"
    replace tier3 = 1 if category == "biotin chromogenic detection kit"
    replace tier3 = 1 if category == "bisulfite conversion kit"
    replace tier3 = 1 if category == "blocking buffers"
    replace tier3 = 1 if category == "blocking reagents"
    replace tier3 = 1 if category == "cell culture antibiotics - amphotericin b"
    replace tier3 = 1 if category == "cell culture antibiotics - ampicillin"
    replace tier3 = 1 if category == "cell culture antibiotics - antimycotic"
    replace tier3 = 1 if category == "cell culture antibiotics - antimycotic solution"
    replace tier3 = 1 if category == "cell culture antibiotics - blasticidin"
    replace tier3 = 1 if category == "cell culture antibiotics - carbenicillin"
    replace tier3 = 1 if category == "cell culture antibiotics - chloramphenicol"
    replace tier3 = 1 if category == "cell culture antibiotics - doxycycline"
    replace tier3 = 1 if category == "cell culture antibiotics - geneticin"
    replace tier3 = 1 if category == "cell culture antibiotics - gentamicin"
    replace tier3 = 1 if category == "cell culture antibiotics - hygromycin"
    replace tier3 = 1 if category == "cell culture antibiotics - kanamycin"
    replace tier3 = 1 if category == "cell culture antibiotics - neomycin"
    replace tier3 = 1 if category == "cell culture antibiotics - nystatin"
    replace tier3 = 1 if category == "cell culture antibiotics - pen-strep"
    replace tier3 = 1 if category == "cell culture antibiotics - penicillin"
    replace tier3 = 1 if category == "cell culture antibiotics - puromycin"
    replace tier3 = 1 if category == "cell culture antibiotics - spectinomycin"
    replace tier3 = 1 if category == "cell culture antibiotics - tetracycline"
    replace tier3 = 1 if category == "cell culture antibiotics - zeocin"
    replace tier3 = 1 if category == "cell culture coating reagents"
    replace tier3 = 1 if category == "cell culture dissociation reagents"
    replace tier3 = 1 if category == "cell culture grade life science water - distilled"
    replace tier3 = 1 if category == "cell culture nutritional supplements - amino acids"
    replace tier3 = 1 if category == "cell culture nutritional supplements - b27"
    replace tier3 = 1 if category == "cell culture nutritional supplements - glucose"
    replace tier3 = 1 if category == "cell culture nutritional supplements - insulin"
    replace tier3 = 1 if category == "cell culture nutritional supplements - its-g"
    replace tier3 = 1 if category == "cell culture nutritional supplements - l-glutamine"
    replace tier3 = 1 if category == "cell culture nutritional supplements - sodium pyruvate"
    replace tier3 = 1 if category == "cell culture nutritional supplements - sugars"
    replace tier3 = 1 if category == "cell culture nutritional supplements - vitamins"
    replace tier3 = 1 if category == "cell culture scaffold kit"
    replace tier3 = 1 if category == "cell culture surface adhesion promoters"
    replace tier3 = 1 if category == "cell imaging signal enhancer"
    replace tier3 = 1 if category == "cell lines"
    replace tier3 = 1 if category == "cell lysis buffers"
    replace tier3 = 1 if category == "cell lysis detergents"
    replace tier3 = 1 if category == "cell lysis enzymes"
    replace tier3 = 1 if category == "cell lysis kits"
    replace tier3 = 1 if category == "cell lysis tubes"
    replace tier3 = 1 if category == "cell permeant chelators"
    replace tier3 = 1 if category == "cell priming kit"
    replace tier3 = 1 if category == "cell proliferation kits"
    replace tier3 = 1 if category == "cell recovery solution"
    replace tier3 = 1 if category == "cell stimulation cocktail"
    replace tier3 = 1 if category == "cell substrates"
    replace tier3 = 1 if category == "cell viability kits"
    replace tier3 = 1 if category == "cell wash buffer"
    replace tier3 = 1 if category == "cell-based reporter assay reagents"
    replace tier3 = 1 if category == "cellular metabolism assay kits"
    replace tier3 = 1 if category == "chip control kit"
    replace tier3 = 1 if category == "click-chemistry protein reaction buffer kit"
    replace tier3 = 1 if category == "collagens - bovine"
    replace tier3 = 1 if category == "colorimetric substrates"
    replace tier3 = 1 if category == "column-based protein purification kit"
    replace tier3 = 1 if category == "depc"
    replace tier3 = 1 if category == "desalting columns"
    replace tier3 = 1 if category == "dna binding buffers"
    replace tier3 = 1 if category == "dna labeling kit"
    replace tier3 = 1 if category == "dna loading dye"
    replace tier3 = 1 if category == "dna purification cartridge"
    replace tier3 = 1 if category == "dna shearing tube"
    replace tier3 = 1 if category == "dna solubilization and binding buffers"
    replace tier3 = 1 if category == "dna topoisomerase i"
    replace tier3 = 1 if category == "dna wash buffer"
    replace tier3 = 1 if category == "dna-salmon sperm"
    replace tier3 = 1 if category == "donor vectors"
    replace tier3 = 1 if category == "dtnb"
    replace tier3 = 1 if category == "dulbecco\'s phosphate-buffered saline (dpbs) buffer"
    replace tier3 = 1 if category == "ecoli"
    replace tier3 = 1 if category == "elution buffer for streptavidin/strep-tactin/avidin resins"
    replace tier3 = 1 if category == "endotoxin removal resins"
    replace tier3 = 1 if category == "flag detection kits"
    replace tier3 = 1 if category == "fluorescein detection blocking reagent"
    replace tier3 = 1 if category == "fluorescein detection buffer"
    replace tier3 = 1 if category == "fluorescein detection kits"
    replace tier3 = 1 if category == "fluorogenic substrates"
    replace tier3 = 1 if category == "fluorophore - calcium indicator"
    replace tier3 = 1 if category == "fluorophore - glutathione indicator"
    replace tier3 = 1 if category == "fluorophore - lysosome indicators"
    replace tier3 = 1 if category == "fluorophore - protein hydrophobicity"
    replace tier3 = 1 if category == "fluorophore - ros indicators"
    replace tier3 = 1 if category == "fluorophore - viability staining solutions"
    replace tier3 = 1 if category == "fluorophore - voltage indicators"
    replace tier3 = 1 if category == "gel loading buffer"
    replace tier3 = 1 if category == "gel loading dye"
    replace tier3 = 1 if category == "gel tracking dyes"
    replace tier3 = 1 if category == "genetically modified mouse strain"
    replace tier3 = 1 if category == "genome amplification kit"
    replace tier3 = 1 if category == "glucose uptake cell-based assays"
    replace tier3 = 1 if category == "gravity flow desalting columns"
    replace tier3 = 1 if category == "gst detection kits"
    replace tier3 = 1 if category == "ha detection kits"
    replace tier3 = 1 if category == "hanks\' balanced salt solution (hbss) buffer"
    replace tier3 = 1 if category == "his-tag imac affinity resins"
    replace tier3 = 1 if category == "his-tag purification buffer set"
    replace tier3 = 1 if category == "human cell lines"
    replace tier3 = 1 if category == "human cytokine antibody array"
    replace tier3 = 1 if category == "human growth factor"
    replace tier3 = 1 if category == "hybridization buffer"
    replace tier3 = 1 if category == "ihc detection kits"
    replace tier3 = 1 if category == "imac columns"
    replace tier3 = 1 if category == "immunohistochemical (ihc) and immunocytochemical (icc) detection kits"
    replace tier3 = 1 if category == "in situ hybridization reagents"
    replace tier3 = 1 if category == "in-vitro translation systems"
    replace tier3 = 1 if category == "insect cell lines"
    replace tier3 = 1 if category == "isotype control"
    replace tier3 = 1 if category == "laemmli sample buffer"
    replace tier3 = 1 if category == "laminin"
    replace tier3 = 1 if category == "ldh cytotoxicity assay"
    replace tier3 = 1 if category == "lds sample buffer"
    replace tier3 = 1 if category == "live cell imaging reagents"
    replace tier3 = 1 if category == "mes-sds buffer"
    replace tier3 = 1 if category == "mops-sds buffer"
    replace tier3 = 1 if category == "mouse cell lines"
    replace tier3 = 1 if category == "mouse nerve growth factors"
    replace tier3 = 1 if category == "mouse-on-mouse immunodetection kits"
    replace tier3 = 1 if category == "mtt"
    replace tier3 = 1 if category == "mycoplasma detection kits"
    replace tier3 = 1 if category == "native-page sample buffer"
    replace tier3 = 1 if category == "nuclease decontaminant"
    replace tier3 = 1 if category == "nuclease enzymes"
    replace tier3 = 1 if category == "nucleic acid labeling/detection kits"
    replace tier3 = 1 if category == "nucleic acid reaction assay microplates"
    replace tier3 = 1 if category == "page sample prep kit"
    replace tier3 = 1 if category == "pap pen"
    replace tier3 = 1 if category == "phalloidin conjugates"
    replace tier3 = 1 if category == "phosphatase inhibitor cocktails"
    replace tier3 = 1 if category == "phosphate-buffered saline (pbs) buffer"
    replace tier3 = 1 if category == "phosphoprotein electrophoresis reagents"
    replace tier3 = 1 if category == "plasmid neutralization buffers"
    replace tier3 = 1 if category == "plasmid resuspension buffers"
    replace tier3 = 1 if category == "plasmid wash buffers"
    replace tier3 = 1 if category == "polylysines"
    replace tier3 = 1 if category == "pre-mixed antibody cocktail"
    replace tier3 = 1 if category == "primary antibodies"
    replace tier3 = 1 if category == "protease inhibitor cocktails"
    replace tier3 = 1 if category == "protease inhibitors"
    replace tier3 = 1 if category == "proteases"
    replace tier3 = 1 if category == "protein denaturants"
    replace tier3 = 1 if category == "protein refolding kit"
    replace tier3 = 1 if category == "rabbit reticulocyte lysate system"
    replace tier3 = 1 if category == "race kits"
    replace tier3 = 1 if category == "recombinant human protein"
    replace tier3 = 1 if category == "recombinant mouse protein"
    replace tier3 = 1 if category == "recombinant proteins"
    replace tier3 = 1 if category == "regeneration buffer for streptavidin/strep-tactin/avidin resins"
    replace tier3 = 1 if category == "rna cap analog reagent"
    replace tier3 = 1 if category == "rna loading dye"
    replace tier3 = 1 if category == "rna-protein pull down kit"
    replace tier3 = 1 if category == "rrna depletion kits"
    replace tier3 = 1 if category == "secondary antibodies"
    replace tier3 = 1 if category == "solubilization reagent"
    replace tier3 = 1 if category == "spin desalting columns"
    replace tier3 = 1 if category == "staining buffer"
    replace tier3 = 1 if category == "streptavidin-biotin binding products"
    replace tier3 = 1 if category == "subcellular protein fractionation kit"
    replace tier3 = 1 if category == "synthetic antibodies"
    replace tier3 = 1 if category == "synthetic plasmids"
    replace tier3 = 1 if category == "t7 in vitro transcription kit"
    replace tier3 = 1 if category == "tag-binding affinity resins"
    replace tier3 = 1 if category == "tbe buffer"
    replace tier3 = 1 if category == "tbe-urea sample buffer"
    replace tier3 = 1 if category == "tissue lysis buffers"
    replace tier3 = 1 if category == "tobacco acid pyrophosphatase (tap)"
    replace tier3 = 1 if category == "total rna"
    replace tier3 = 1 if category == "transcription factor extraction buffer set"
    replace tier3 = 1 if category == "transforming growth factor"
    replace tier3 = 1 if category == "tris-acetate-edta (tae) buffer"
    replace tier3 = 1 if category == "tris-glycine buffer"
    replace tier3 = 1 if category == "tris-glycine-sds (tgs) buffer"
    replace tier3 = 1 if category == "tris-tricine-sds buffer"
    replace tier3 = 1 if category == "viability stains"
    replace tier3 = 1 if category == "viability/cytotoxicity kit"
    replace tier3 = 1 if category == "yeast shuttle vector"
    replace tier3 = 1 if category == "yeast strains"
    replace tier3 = 1 if category == "yeast trna"

    gen treated_strict = (tier1 == 1)
    gen treated_1and2  = (tier1 == 1 | tier2 == 1)
    gen treated    = (tier1 == 1 | tier2 == 1 | tier3 == 1)

    * Summary
    tab tier1
    tab tier2
    tab tier3
    tab treated
    gen keep  = (support >= 25 & precision >= 0.80 & recall >= 0.80) //| (inrange(support, 10, 25) & precision >= 0.9 & recall >=0.90) 
    save ../output/categories_`embed', replace
end
main