# 5_validate_utdallas.py (Supports UT Dallas, UMich, and combined validation)
"""
Validates the output of 3_predict_product_markets.py against ground truth labels.

This script does NOT re-run any models. It READS the predictions
from the CSV file(s) generated by Script 3.

Uses positional alignment to safely match predictions to ground truth.

ASSUMPTION: You have already run 3_predict_product_markets.py on
the relevant source(s).
"""
import pandas as pd
import os
import argparse
from sklearn.metrics import classification_report

import config


def validate_source(source_name, classified_filepath, truth_path, truth_loader,
                    gatekeeper_name, expert_choice, min_support):
    """Validate predictions for a single data source."""
    print(f"\n{'='*80}")
    print(f"--- Validating: {source_name} ---")

    try:
        print(f"  Loading predictions from: {classified_filepath}")
        df_classified = pd.read_csv(classified_filepath)
    except FileNotFoundError:
        print(f"  SKIPPED: Prediction file not found: {classified_filepath}")
        print(f"  Run: python 3_predict_product_markets.py {source_name.lower()} --gatekeeper {gatekeeper_name} --expert {expert_choice}")
        return None

    try:
        print(f"  Loading true labels from: {truth_path}")
        df_validation = truth_loader()
    except FileNotFoundError:
        print(f"  SKIPPED: Ground truth file not found: {truth_path}")
        return None

    if len(df_classified) != len(df_validation):
        print(f"  ERROR: Row count mismatch ({len(df_classified)} vs {len(df_validation)}).")
        return None

    print(f"  Aligned {len(df_classified)} predictions to {len(df_validation)} ground truth rows.")
    y_pred = df_classified['predicted_market'].fillna("unclassified")
    y_true_full = df_validation[config.UT_CAT_COL]

    # Simplify true labels
    is_true_nonlab = y_true_full.str.contains(config.NONLAB_REGEX, na=False)
    y_true_simplified = y_true_full.copy()
    y_true_simplified.loc[is_true_nonlab] = 'Non-Lab'
    y_true_simplified = y_true_simplified.fillna("unclassified")

    # Generate classification report
    report_dict = classification_report(y_true_simplified, y_pred, zero_division=0, output_dict=True)
    df_report = pd.DataFrame(report_dict).transpose()
    df_report['support'] = df_report['support'].astype(int)

    # Save reports
    base_name = f"gatekeeper_{gatekeeper_name}_expert_{expert_choice}"
    source_tag = source_name.lower().replace(' + ', '_').replace(' ', '_')

    path_full = os.path.join(config.OUTPUT_DIR, f"{source_tag}_full_report_{base_name}.csv")
    path_summary = os.path.join(config.OUTPUT_DIR, f"{source_tag}_summary_report_{base_name}.txt")

    df_report.to_csv(path_full)
    print(f"  Full report saved to: {path_full}")

    df_summary = df_report[df_report['support'] >= min_support]
    with open(path_summary, 'w') as f:
        f.write(f"Summary Performance Report: {source_name} (Support >= {min_support})\n")
        f.write(f"Gatekeeper: {gatekeeper_name}, Expert: {expert_choice}\n")
        f.write(f"Variant: {config.VARIANT}\n")
        f.write("=" * 70 + "\n")
        f.write(df_summary.to_string())
    print(f"  Summary report saved to: {path_summary}")

    # Print key metrics
    for label in ['macro avg', 'weighted avg']:
        if label in df_report.index:
            row = df_report.loc[label]
            print(f"  {label}: precision={row['precision']:.4f}  recall={row['recall']:.4f}  f1={row['f1-score']:.4f}")

    return df_report


def main(gatekeeper_name: str, expert_choice: str, min_support: int = 25):
    print("=" * 80)
    print(f"--- Validation [Variant: {config.VARIANT}] ---")
    print(f"  Gatekeeper: {gatekeeper_name}  |  Expert: {expert_choice}  |  Min support: {min_support}")

    # Always validate UT Dallas
    utd_classified = os.path.join(config.OUTPUT_DIR,
        f"utdallas_merged_clean_classified_with_{expert_choice}.csv")
    validate_source(
        "utdallas", utd_classified, config.UT_DALLAS_MERGED_CLEAN_PATH,
        lambda: pd.read_parquet(config.UT_DALLAS_MERGED_CLEAN_PATH),
        gatekeeper_name, expert_choice, min_support,
    )

    # Validate UMich if the classified predictions file exists.
    # Gated on file existence (not USE_UMICH) so `baseline` can also evaluate
    # on UMich data after running `3_predict_product_markets.py umich ...`.
    umich_classified = os.path.join(config.OUTPUT_DIR,
        f"umich_merged_clean_classified_with_{expert_choice}.csv")
    if os.path.exists(umich_classified) and os.path.exists(config.UMICH_MERGED_CLEAN_PATH):
        validate_source(
            "umich", umich_classified, config.UMICH_MERGED_CLEAN_PATH,
            lambda: pd.read_parquet(config.UMICH_MERGED_CLEAN_PATH),
            gatekeeper_name, expert_choice, min_support,
        )

        # Combined: stack both
        print(f"\n{'='*80}")
        print("--- Validating: UT Dallas + UMich (combined) ---")
        try:
            df_utd_cls = pd.read_csv(utd_classified)
            df_um_cls = pd.read_csv(umich_classified)
            df_utd_truth = pd.read_parquet(config.UT_DALLAS_MERGED_CLEAN_PATH)
            df_um_truth = pd.read_parquet(config.UMICH_MERGED_CLEAN_PATH)

            # Build a single combined dataframe with a `university` column.
            # Predictions (from script 3) and ground truth (from script 0)
            # are positionally aligned, so we attach the truth label as a
            # column on the classified rows.
            df_utd_full = df_utd_cls.copy()
            df_utd_full['university'] = 'ut_dallas'
            df_utd_full['true_category'] = df_utd_truth[config.UT_CAT_COL].values

            df_um_full = df_um_cls.copy()
            df_um_full['university'] = 'umich'
            df_um_full['true_category'] = df_um_truth[config.UT_CAT_COL].values

            df_combined = pd.concat([df_utd_full, df_um_full], ignore_index=True)

            base_name = f"gatekeeper_{gatekeeper_name}_expert_{expert_choice}"
            combined_path = os.path.join(
                config.OUTPUT_DIR,
                f"combined_merged_classified_with_{expert_choice}.csv",
            )
            df_combined.to_csv(combined_path, index=False)
            print(f"  Combined merged file saved to: {combined_path}")

            # Build the classification report off the combined frame
            y_pred = df_combined['predicted_market'].fillna("unclassified")
            y_true_full = df_combined['true_category']
            is_true_nonlab = y_true_full.astype(str).str.contains(config.NONLAB_REGEX, na=False)
            y_true_simplified = y_true_full.copy()
            y_true_simplified.loc[is_true_nonlab] = 'Non-Lab'
            y_true_simplified = y_true_simplified.fillna("unclassified")

            report_dict = classification_report(y_true_simplified, y_pred, zero_division=0, output_dict=True)
            df_report = pd.DataFrame(report_dict).transpose()
            df_report['support'] = df_report['support'].astype(int)

            path_full = os.path.join(config.OUTPUT_DIR, f"combined_full_report_{base_name}.csv")
            df_report.to_csv(path_full)
            print(f"  Combined report saved to: {path_full}")

            n_utd = len(df_utd_cls)
            n_um = len(df_um_cls)
            print(f"  Combined: {n_utd} UT Dallas + {n_um} UMich = {n_utd + n_um} total")
            for label in ['macro avg', 'weighted avg']:
                if label in df_report.index:
                    row = df_report.loc[label]
                    print(f"  {label}: precision={row['precision']:.4f}  recall={row['recall']:.4f}  f1={row['f1-score']:.4f}")

        except FileNotFoundError as e:
            print(f"  SKIPPED combined validation: {e}")

    print(f"\n{'='*80}")
    print("--- Validation Complete ---")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Validate pipeline output against ground truth."
    )
    parser.add_argument("--gatekeeper", type=str, required=True, choices=['tfidf', 'bert'])
    parser.add_argument("--expert", type=str, required=True, choices=['tfidf', 'bert'])
    parser.add_argument("--min_support", type=int, default=25)
    args = parser.parse_args()
    main(gatekeeper_name=args.gatekeeper, expert_choice=args.expert, min_support=args.min_support)
